import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ThemeProvider } from '@/components/ThemeProvider'
import Header from '@/components/Header'
import { Toaster } from '@/components/ui/toaster'
import SplashScreenWrapper from '@/components/splash/SplashScreenWrapper'
import { SupabaseProvider } from '@/contexts/SupabaseContext'
import { UserStocksProvider } from '@/contexts/UserStocksContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Stockfolio',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SplashScreenWrapper>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <SupabaseProvider>
              <UserStocksProvider>
                <Header />
                {children}
              </UserStocksProvider>
            </SupabaseProvider>
            <Toaster />
          </ThemeProvider>
        </SplashScreenWrapper>
      </body>
    </html>
  )
}
